'use client';
import { useEffect,useRef,useState } from 'react';
import { Copy,FileText,Link2,X } from 'lucide-react';
import { clientRequest } from '@/lib/client-request';
type Row=Record<string,any>;
const path='/api/integrations/granola';
const names:Row={query_granola_meetings:'Find relevant notes',list_meetings:'Browse meetings',get_meetings:'Read selected meetings'};
const label=(value:string)=>value.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());

export function ProviderConnections({spaces,agents,onShared,onAddAgent,onDotsSetup}:{spaces:Row[];agents:Row[];onShared:()=>void;onAddAgent:(provider:string)=>void;onDotsSetup:()=>void}){
  const [status,setStatus]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[confirm,setConfirm]=useState(false);
  const [museOpen,setMuseOpen]=useState(false),[instinctOpen,setInstinctOpen]=useState(false);
  async function refresh(){try{setStatus(await clientRequest(path));setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void refresh().then(()=>{if(new URLSearchParams(window.location.search).get('granola')==='not_connected')setError('Granola sign-in did not complete. Please reconnect; no notes were shared.');if(new URLSearchParams(window.location.search).has('granola'))window.history.replaceState(null,'','/?view=connections');});},[]);
  async function connect(){setBusy(true);setError('');try{const result=await clientRequest(path,'connect',{});window.location.assign(result.authorization_url);}catch(e){setError((e as Error).message);setBusy(false);}}
  async function disconnect(){setBusy(true);setError('');try{setStatus(await clientRequest(path,'disconnect',{}));setConfirm(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="provider-section" aria-label="Account connections">
    <div className="section-heading"><div><h2>Connect accounts and agents</h2><p className="muted">Bring selected notes into a space, and let your personal agent use Accord.</p></div></div>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="provider-grid">
      <article className="provider-card"><div className="provider-card-heading"><Link2 size={22}/><h3>Meta Muse</h3><span className="badge pending">Connection unverified</span></div><p>Prepare Accord for your Muse agent. Muse’s connector onboarding requires sign-in and review before we can verify its connection.</p><div className="heading-actions"><button className="button primary" onClick={()=>setMuseOpen(true)}>Set up Muse</button><a className="button quiet" href="https://muse.ai/platform" target="_blank" rel="noreferrer">Muse connector platform</a></div><p className="field-help">Accord is not yet available or verified in Muse.</p></article>
      <article className="provider-card"><div className="provider-card-heading"><Link2 size={22}/><h3>Instinct</h3><span className="badge pending">Connection unverified</span></div><p>Prepare a profile for your Instinct personal assistant, then check its available integrations.</p><div className="heading-actions"><button className="button primary" onClick={()=>setInstinctOpen(true)}>Set up Instinct</button><a className="button quiet" href="https://instinct.com/" target="_blank" rel="noreferrer">About Instinct</a></div><p className="field-help">A supported Accord connection in Instinct still needs verification.</p></article>
      <article className="provider-card"><div className="provider-card-heading"><FileText size={22}/><h3>Granola</h3><span className={`badge ${status?.status==='connected'?'connected':'pending'}`}>{status?.status==='connected'?'Connected':status?'Not connected':'Checking…'}</span></div><p>Find meeting notes privately. Review an excerpt before sharing it with people and agents in a space.</p>{status?.account_label&&<details><summary>Connected account and workspace</summary><pre>{status.account_label}</pre></details>}
        {confirm?<div className="provider-confirm"><p>Disconnect stops future reads and clears Accord’s saved credentials. Shared excerpts remain in their spaces; stop sharing those separately.</p><div className="heading-actions"><button className="button secondary" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={disconnect}>{busy?'Disconnecting…':'Disconnect Granola'}</button></div></div>:<div className="heading-actions">{status?.status==='connected'?<><button className="button primary" disabled={busy} onClick={()=>setOpen(true)}>Choose notes</button><button className="button quiet" disabled={busy} onClick={connect}>{busy?'Opening Granola…':'Sign in again'}</button><button className="button quiet" disabled={busy} onClick={()=>setConfirm(true)}>Disconnect</button></>:<button className="button primary" disabled={busy||!status?.configured} onClick={connect}>{busy?'Opening Granola…':'Connect Granola'}</button>}</div>}
        {status&&!status.configured&&<p className="field-help">Account sign-in is temporarily unavailable.</p>}<p className="field-help">Granola controls note access through your account, plan and active workspace.</p>
      </article>
      <article className="provider-card"><div className="provider-card-heading"><Link2 size={22}/><h3>OpenAI dots</h3><span className="badge pending">Setup available</span></div><p>Your dot can use supported plugins enabled for its account. Enable Accord, then ask your dot to connect its profile.</p><div className="heading-actions"><button className="button secondary" onClick={onDotsSetup}>Set up dots</button><button className="button quiet" onClick={()=>onAddAgent('OpenAI dots')}>Add a dots profile</button></div><p className="field-help">Accord has been tested in Codex. Use from a dot still needs verification.</p></article>
    </div>
    {open&&<GranolaNotesDialog spaces={spaces} onClose={()=>setOpen(false)} onShared={()=>{onShared();void refresh();}}/>}
    {museOpen&&<MuseSetupDialog agents={agents} onClose={()=>setMuseOpen(false)} onCreateProfile={()=>{setMuseOpen(false);onAddAgent('Meta Muse');}}/>}
    {instinctOpen&&<InstinctSetupDialog agents={agents} onClose={()=>setInstinctOpen(false)} onCreateProfile={()=>{setInstinctOpen(false);onAddAgent('Instinct');}}/>}
  </section>;
}

export function MuseSetupDialog({agents,onClose,onCreateProfile,initialProfileId=''}:{agents:Row[];onClose:()=>void;onCreateProfile:()=>void;initialProfileId?:string}){
  const ref=useRef<HTMLDialogElement>(null),[profileId,setProfileId]=useState(initialProfileId),[copied,setCopied]=useState(''),[copyFallback,setCopyFallback]=useState('');
  const profiles=agents.filter(a=>a.status!=='revoked'&&['muse','meta muse'].includes(String(a.provider).trim().toLowerCase()));
  const selected=profiles.find(a=>a.id===profileId),endpoint=typeof window==='undefined'?'':window.location.origin+'/mcp';
  const prompt=selected?`Use the Accord connector to list my agent profiles. Confirm that the profile named ${JSON.stringify(selected.name)} with ID ${selected.id} belongs to my signed-in account and is active, then connect only that profile. Read every page of its accepted guidance and current inbox. Preserve each item’s scope, version and source attribution; use only relevant current guidance. Tell me what you can access before doing any work. Keep proposed guidance for my review. If Accord’s tools are unavailable or any step fails, stop and explain; do not claim a successful connection.`:'';
  useEffect(()=>{const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null;ref.current?.showModal();return()=>queueMicrotask(()=>{if(document.querySelector('dialog[open]'))return;if(trigger?.isConnected)trigger.focus();});},[]);
  async function copy(value:string,message:string){setCopied('');setCopyFallback('');try{await navigator.clipboard.writeText(value);setCopied(message);}catch{setCopyFallback(value);}}
  return <dialog ref={ref} className="muse-dialog" aria-labelledby="muse-setup-title" aria-describedby="muse-setup-description" onCancel={onClose}>
    <div className="dialog-heading"><div><span className="eyebrow">ACCORD / MUSE</span><h2 id="muse-setup-title">Set up Meta Muse</h2></div><button className="icon-button" aria-label="Close Muse setup" onClick={onClose}><X size={20}/></button></div>
    <p id="muse-setup-description" className="dialog-description">Prepare your profile here. The connection still requires Muse’s supported onboarding and a real tool call.</p>
    <section className="muse-setup-step" aria-labelledby="muse-provider-heading"><h3 id="muse-provider-heading">1. Open Muse’s connector setup</h3><p>Muse requires a work-email sign-in before showing its submission requirements. Accord has not been submitted or approved.</p><a className="button secondary" href="https://muse.ai/platform" target="_blank" rel="noreferrer">Open Muse connector platform</a></section>
    <section className="muse-setup-step" aria-labelledby="muse-profile-heading"><h3 id="muse-profile-heading">2. Choose your Accord profile</h3><p>A profile keeps this agent’s participation together. Creating one does not connect your Muse account.</p>{profiles.length>0&&<div className="form-field"><label htmlFor="muse-profile">Muse profile</label><select id="muse-profile" value={profileId} onChange={e=>{setProfileId(e.target.value);setCopied('');setCopyFallback('');}}><option value="">Choose a profile</option>{profiles.map(a=><option key={a.id} value={a.id}>{a.name} · {a.status==='connected'?'Agent activity recorded':'Awaiting a connection'}</option>)}</select></div>}<button className="button quiet" onClick={onCreateProfile}>Create a Muse profile</button></section>
    <section className="muse-setup-step" aria-labelledby="muse-test-heading"><h3 id="muse-test-heading">3. Verify from Muse</h3><p>Once Accord is available to your account in Muse, authorize it there. Use this prompt to choose your profile and check access.</p>{selected?<><label className="small-label" htmlFor="muse-start-prompt">Prompt for your Muse agent</label><textarea id="muse-start-prompt" className="copy-text" readOnly rows={5} value={prompt}/><button className="button secondary" onClick={()=>void copy(prompt,'Muse setup prompt copied.')}><Copy size={15}/>Copy setup prompt</button></>:<p className="field-help">Choose or create a profile to prepare its setup prompt.</p>}<p className="field-help">Return to Connections after the call. An activity status confirms an authenticated Accord call, not the caller’s vendor or a change to Muse’s private memory.</p></section>
    <details className="muse-connection-details"><summary>Connection details for Muse onboarding</summary><p>Use these only if Muse’s onboarding asks for an MCP server. Its consumer connection requirements still need verification.</p><label className="small-label" htmlFor="muse-server-url">Accord MCP address</label><input id="muse-server-url" readOnly value={endpoint}/><button className="button quiet" onClick={()=>void copy(`MCP server: ${endpoint}\nOAuth resource: ${endpoint}\nDiscovery: ${endpoint.replace(/\/mcp$/,'')}/.well-known/accord.json\nAuthentication: Accord account sign-in managed by Sites${selected?`\nProfile: ${selected.name}\nProfile ID: ${selected.id}`:''}`,'Connection details copied.')}><Copy size={15}/>Copy connection details</button><p className="field-help">Sign in with the Accord account that owns the selected profile. The Site is private; a connector does not grant new people access.</p></details>
    {copied&&<p role="status" className="source-success">{copied}</p>}{copyFallback&&<div className="form-field"><label htmlFor="muse-copy-fallback">Select and copy this text</label><textarea id="muse-copy-fallback" readOnly rows={6} value={copyFallback}/></div>}
    <div className="dialog-actions"><button className="button secondary" onClick={onClose}>Close</button></div>
  </dialog>;
}

export function InstinctSetupDialog({agents,onClose,onCreateProfile,initialProfileId=''}:{agents:Row[];onClose:()=>void;onCreateProfile:()=>void;initialProfileId?:string}){
  const ref=useRef<HTMLDialogElement>(null),[profileId,setProfileId]=useState(initialProfileId),[copied,setCopied]=useState(''),[copyFallback,setCopyFallback]=useState('');
  const profiles=agents.filter(a=>a.status!=='revoked'&&['instinct','instinct ai'].includes(String(a.provider).trim().toLowerCase()));
  const selected=profiles.find(a=>a.id===profileId),endpoint=typeof window==='undefined'?'':window.location.origin+'/mcp';
  const prompt=selected?`First check whether Instinct offers a supported, authenticated Accord connector. If it does not, stop and explain what is missing; do not claim a connection or substitute browser activity for a connector. If Accord tools are available and authorized by me, list my agent profiles. Confirm that the profile named ${JSON.stringify(selected.name)} with ID ${selected.id} belongs to my signed-in account and is active, then connect only that profile. Read every page of its accepted guidance and current inbox. Preserve scope, version and source attribution; use only relevant current guidance. Tell me what you can access before doing any work. Keep proposed guidance for my review. If any step fails, stop and explain.`:'';
  useEffect(()=>{const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null;ref.current?.showModal();return()=>queueMicrotask(()=>{if(document.querySelector('dialog[open]'))return;if(trigger?.isConnected)trigger.focus();});},[]);
  async function copy(value:string,message:string){setCopied('');setCopyFallback('');try{await navigator.clipboard.writeText(value);setCopied(message);}catch{setCopyFallback(value);}}
  return <dialog ref={ref} className="muse-dialog" aria-labelledby="instinct-setup-title" aria-describedby="instinct-setup-description" onCancel={onClose}>
    <div className="dialog-heading"><div><span className="eyebrow">ACCORD / INSTINCT</span><h2 id="instinct-setup-title">Set up Instinct</h2></div><button className="icon-button" aria-label="Close Instinct setup" onClick={onClose}><X size={20}/></button></div>
    <p id="instinct-setup-description" className="dialog-description">Prepare your profile here. A live connection depends on Instinct’s supported integrations and a verified call.</p>
    <section className="muse-setup-step" aria-labelledby="instinct-provider-heading"><h3 id="instinct-provider-heading">1. Check Instinct’s integrations</h3><p>Sign into your existing Instinct account and check its integration settings. Its public documentation does not confirm custom connectors or remote MCP support.</p><a className="button secondary" href="https://app.instinct.com/login" target="_blank" rel="noreferrer">Open Instinct</a></section>
    <section className="muse-setup-step" aria-labelledby="instinct-profile-heading"><h3 id="instinct-profile-heading">2. Choose your Accord profile</h3><p>A profile organizes your assistant’s participation. Creating one does not connect your Instinct account.</p>{profiles.length>0&&<div className="form-field"><label htmlFor="instinct-profile">Instinct profile</label><select id="instinct-profile" value={profileId} onChange={e=>{setProfileId(e.target.value);setCopied('');setCopyFallback('');}}><option value="">Choose a profile</option>{profiles.map(a=><option key={a.id} value={a.id}>{a.name} · {a.status==='connected'?'Agent activity recorded':'Awaiting a connection'}</option>)}</select></div>}<button className="button quiet" onClick={onCreateProfile}>Create an Instinct profile</button></section>
    <section className="muse-setup-step" aria-labelledby="instinct-test-heading"><h3 id="instinct-test-heading">3. Verify from Instinct</h3><p>If Instinct supports Accord, authorize it through the supported setup before using this prompt. It checks access to the profile you choose.</p>{selected?<><label className="small-label" htmlFor="instinct-start-prompt">Prompt for your Instinct agent</label><textarea id="instinct-start-prompt" className="copy-text" readOnly rows={5} value={prompt}/><button className="button secondary" onClick={()=>void copy(prompt,'Instinct setup prompt copied.')}><Copy size={15}/>Copy setup prompt</button></>:<p className="field-help">Choose or create a profile to prepare its setup prompt.</p>}<p className="field-help">Copying a prompt does not connect an account. An activity status confirms an authenticated Accord call; it does not identify the calling provider or change Instinct’s private memory.</p></section>
    <details className="muse-connection-details"><summary>Connection details for compatible integrations</summary><p>Use these only if Instinct supports a remote MCP connection with Accord sign-in. Instinct compatibility has not been verified.</p><label className="small-label" htmlFor="instinct-server-url">Accord MCP address</label><input id="instinct-server-url" readOnly value={endpoint}/><button className="button quiet" onClick={()=>void copy(`MCP server: ${endpoint}\nOAuth resource: ${endpoint}\nDiscovery: ${endpoint.replace(/\/mcp$/,'')}/.well-known/accord.json\nAuthentication: Accord account sign-in managed by Sites${selected?`\nProfile: ${selected.name}\nProfile ID: ${selected.id}`:''}`,'Connection details copied.')}><Copy size={15}/>Copy connection details</button><p className="field-help">Use the Accord account that owns this profile. The Site remains private. No Instinct credentials are collected here.</p></details>
    {copied&&<p role="status" className="source-success">{copied}</p>}{copyFallback&&<div className="form-field"><label htmlFor="instinct-copy-fallback">Select and copy this text</label><textarea id="instinct-copy-fallback" readOnly rows={6} value={copyFallback}/></div>}
    <div className="dialog-actions"><button className="button secondary" onClick={onClose}>Close</button></div>
  </dialog>;
}

export function GranolaNotesDialog({spaces,spaceId,onClose,onShared}:{spaces:Row[];spaceId?:string;onClose:()=>void;onShared:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),[tools,setTools]=useState<Row[]>([]),[toolName,setToolName]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [preview,setPreview]=useState<Row|null>(null),[content,setContent]=useState(''),[title,setTitle]=useState('Granola meeting excerpt'),[selectedSpace,setSelectedSpace]=useState(spaceId||''),[result,setResult]=useState<string|null>(null);
  const schema=tools.find(t=>t.name===toolName)?.inputSchema;
  useEffect(()=>{const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null;ref.current?.showModal();let active=true;void clientRequest(path,'tools',{}).then(r=>{if(!active)return;setTools(r.tools);setToolName(r.tools.find((t:Row)=>t.name==='query_granola_meetings')?.name||r.tools[0]?.name||'');}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;queueMicrotask(()=>{if(trigger?.isConnected)trigger.focus();});};},[]);
  async function read(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setBusy(true);setError('');setResult(null);setPreview(null);setContent('');
    const form=new FormData(e.currentTarget),parameters:Row={};
    try{
      for(const [key,s] of Object.entries(schema?.properties||{}) as [string,Row][]){const raw=form.get(key);const type=Array.isArray(s.type)?s.type.find((t:string)=>t!=='null'):s.type;const required=schema?.required?.includes(key);if(raw===null||raw===''&&!required)continue;if(s.enum)parameters[key]=JSON.parse(String(raw));else if(type==='boolean')parameters[key]=raw==='true';else if(type==='number'||type==='integer')parameters[key]=Number(raw);else if(type==='array')parameters[key]=String(raw).split(',').map(v=>v.trim()).filter(Boolean);else parameters[key]=raw;}
      const p=await clientRequest(path,'preview',{tool:toolName,parameters});setPreview(p);setContent(p.content);setTitle('Granola meeting excerpt');
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function share(e:React.FormEvent){e.preventDefault();if(!preview)return;setBusy(true);setError('');try{const saved=await clientRequest(path,'share',{draft_id:preview.draft_id,space_id:selectedSpace,title,content});setResult(saved.replayed?'Earlier sharing recovered. No duplicate source was created.':'The selected excerpt is now shared with this space.');setPreview(null);setContent('');onShared();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const supported=schema&&!schema.anyOf&&!schema.oneOf&&!schema.allOf&&Object.values(schema.properties||{}).every((s:any)=>{const type=Array.isArray(s.type)?s.type.find((t:string)=>t!=='null'):s.type;return !s.$ref&&!s.anyOf&&!s.oneOf&&!s.allOf&&(['string','boolean','number','integer'].includes(type)||(type==='array'&&s.items?.type==='string'));});
  return <dialog ref={ref} className="granola-dialog" aria-labelledby="granola-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="dialog-heading"><div><span className="eyebrow">GRANOLA / PRIVATE PREVIEW</span><h2 id="granola-title">Choose what carries forward</h2></div><button className="icon-button" aria-label="Close Granola notes" disabled={busy} onClick={onClose}><X size={20}/></button></div>
    <p className="dialog-description">Only you can see this preview. Nothing is shared with a relationship until you review the excerpt and confirm its destination.</p>
    {loading?<p role="status">Loading available meeting tools…</p>:tools.length>0?<form onSubmit={read} className="granola-search"><div className="form-field"><label htmlFor="granola-method">Read your notes</label><select id="granola-method" disabled={busy} value={toolName} onChange={e=>{setToolName(e.target.value);setPreview(null);setContent('');setError('');}}>{tools.map(t=><option value={t.name} key={t.name}>{names[t.name]||t.name}</option>)}</select></div>
      {supported?Object.entries(schema.properties||{}).map(([key,s]:[string,any])=>{const type=Array.isArray(s.type)?s.type.find((t:string)=>t!=='null'):s.type;const required=schema.required?.includes(key);return <div className="form-field" key={toolName+key}><label htmlFor={'granola-'+key}>{s.title||label(key)}{!required&&<span> · optional</span>}</label>{s.enum?<select id={'granola-'+key} name={key} required={required} disabled={busy} defaultValue={s.default!==undefined?JSON.stringify(s.default):''}><option value="">Choose one</option>{s.enum.map((value:any)=><option key={JSON.stringify(value)} value={JSON.stringify(value)}>{String(value)}</option>)}</select>:type==='boolean'?<select id={'granola-'+key} name={key} disabled={busy} required={required} defaultValue={s.default!==undefined?String(s.default):''}><option value="">Choose one</option><option value="true">Yes</option><option value="false">No</option></select>:<input id={'granola-'+key} name={key} disabled={busy} required={required} type={type==='number'||type==='integer'?'number':'text'} step={type==='integer'?1:'any'} min={s.minimum} max={s.maximum} maxLength={Math.min(s.maxLength||2000,2000)} defaultValue={s.default===undefined?'':type==='array'?s.default.join(', '):String(s.default)}/>}<p className="field-help">{s.description}{type==='array'?' Separate values with commas.':''}</p></div>;}):<p className="field-help">This Granola tool uses filters Accord does not yet support. Choose another reading method.</p>}
      <button className="button secondary" disabled={busy||!supported}>{busy?'Reading…':'Preview notes'}</button></form>:null}
    {error&&<p className="error" role="alert">{error}</p>}{result&&<p className="source-success" role="status">{result}</p>}
    {preview&&<form className="granola-review" onSubmit={share}><h3>Review the excerpt</h3><p className="field-help">Keep only what this relationship needs. Granola search answers may summarize notes; review their wording and citations. This preview expires after 20 minutes.</p><div className="form-field"><label htmlFor="granola-share-space">Share with this space</label><select id="granola-share-space" required disabled={busy} value={selectedSpace} onChange={e=>setSelectedSpace(e.target.value)}><option value="">Choose a space</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="form-field"><label htmlFor="granola-excerpt-title">Excerpt title</label><input id="granola-excerpt-title" required maxLength={120} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="form-field"><label htmlFor="granola-excerpt">Selected notes to share</label><textarea id="granola-excerpt" rows={9} required maxLength={18500} disabled={busy} value={content} onChange={e=>setContent(e.target.value)}/></div><p className="note">People and agents with access to the selected space can read the saved excerpt. It is an imported copy; edits or removal in Granola do not update it automatically. Guidance still needs a separate review.</p><button className="button primary" disabled={busy||!spaces.length}>{busy?'Sharing…':'Share reviewed excerpt'}</button></form>}
    <div className="dialog-actions"><button className="button quiet" disabled={busy} onClick={onClose}>Close</button></div>
  </dialog>;
}
