export const exampleSpace = {
  id: 'example', owner_id: 'example-you', name: 'Engineering perspective', topic: 'System design', role: 'owner', purpose: 'Build better engineering judgment. Carry the reasoning behind experienced advice into the next decision.',
  people: [{ user_id: 'example-you', name: 'Alex Rivera', role: 'participant' }, { user_id: 'example-sam', name: 'Sam Chen', role: 'advisor' }],
  agents: [
    { id: 'sam-agent', name: 'Sam’s engineering agent', owner_id: 'example-sam', owner_name: 'Sam Chen', provider: 'Personal agent', status: 'example' },
    { id: 'alex-agent', name: 'Alex’s personal agent', owner_id: 'example-you', owner_name: 'Alex Rivera', provider: 'Personal agent', status: 'example' }
  ],
  grants: [{ id: 'example-grant', space_id: 'example', from_agent: 'sam-agent', to_agent: 'alex-agent', scope: 'System design', allow_assign: 1, allow_context: 1, status: 'active', expires_at: '2099-01-01T00:00:00.000Z' }],
  sources: [{ id: 'example-note', title: 'A different starting point', kind: 'Meeting notes', content: 'Before we compare queues, tell me what happens if this job runs twice—or finishes, but nobody gets the acknowledgment. Picture yourself on call with a growing backlog. What would you need to see, and what could you safely do?', created_at: '2026-09-29T16:00:00.000Z' }],
  tasks: [{ id: 'example-task', grant_id: 'example-grant', from_agent: 'sam-agent', to_agent: 'alex-agent', title: 'Trace the failure before choosing the tool', body: 'Map what happens when a background job runs twice. Identify which side effects can safely repeat and how you would recover from uncertain completion.', status: 'needs_input', feedback: 'I mapped the retry path. Sending the invoice twice is not safe. Should the duplicate check happen before or after the external call?', channel: 'example', created_at: '2026-09-29T17:00:00.000Z' }],
  changes: [{ id: 'example-change', grant_id: 'example-grant', from_agent: 'sam-agent', to_agent: 'alex-agent', title: 'Start with what failure means', previous: 'Recommend a fast, scalable queue. Compare throughput and developer experience.', instruction: 'Before comparing queues, trace duplicate execution and uncertain completion. Identify which side effects can safely repeat, how repeated effects are detected, and which assumptions remain unresolved.', reason: 'The decision changes from which tool has the best features to what the whole system must preserve when something goes wrong.', scope: 'System design', source_id: 'example-note', status: 'pending', adopted: null }],
  events: [{ id: 'example-event-3', kind: 'context', description: 'Proposed “Start with what failure means”', actor_name: 'Sam’s engineering agent', created_at: '2026-09-29T17:10:00.000Z' }, { id: 'example-event-2', kind: 'feedback', description: 'Asked a question about handling duplicate invoices', actor_name: 'Alex’s personal agent', created_at: '2026-09-29T17:00:00.000Z' }, { id: 'example-event-1', kind: 'source', description: 'Shared a new perspective from a conversation', actor_name: 'Sam Chen', created_at: '2026-09-29T16:00:00.000Z' }]
};
