import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const people = sqliteTable('people', { id: text().primaryKey(), email: text().notNull(), name: text().notNull() });
export const spaces = sqliteTable('spaces', { id: text().primaryKey(), owner_id: text().notNull(), name: text().notNull(), purpose: text().notNull(), topic: text().notNull(), created_at: text().notNull(), membership_version: integer().notNull().default(0) });
export const members = sqliteTable('members', { space_id: text().notNull().references(() => spaces.id), user_id: text().notNull(), role: text().notNull(), membership_key: text().notNull().default('legacy') }, t => [primaryKey({ columns: [t.space_id, t.user_id] }), index('members_user').on(t.user_id)]);
export const agents = sqliteTable('agents', { id: text().primaryKey(), owner_id: text().notNull(), name: text().notNull(), provider: text().notNull(), status: text().notNull().default('pending'), last_seen_at: text(), created_at: text().notNull() }, t => [index('agents_owner').on(t.owner_id)]);
export const spaceAgents = sqliteTable('space_agents', { space_id: text().notNull().references(() => spaces.id), agent_id: text().notNull().references(() => agents.id) }, t => [primaryKey({ columns: [t.space_id, t.agent_id] })]);
export const grants = sqliteTable('grants', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), from_agent: text().notNull().references(() => agents.id), to_agent: text().notNull().references(() => agents.id), scope: text().notNull(), allow_assign: integer().notNull(), allow_context: integer().notNull(), status: text().notNull(), expires_at: text().notNull(), issued_by: text(), request_key: text(), request_hash: text(), created_at: text().notNull() }, t => [index('grants_space').on(t.space_id), uniqueIndex('grants_issuer_request').on(t.issued_by,t.request_key)]);
export const sources = sqliteTable('sources', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), title: text().notNull(), content: text().notNull(), kind: text().notNull(), created_by: text().notNull(), created_at: text().notNull(), status: text().notNull().default('active'), version: integer().notNull().default(0), updated_by: text(), updated_at: text() }, t => [index('sources_space').on(t.space_id)]);
export const tasks = sqliteTable('tasks', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), grant_id: text().notNull().references(() => grants.id), from_agent: text().notNull(), to_agent: text().notNull(), title: text().notNull(), body: text().notNull(), status: text().notNull(), feedback: text().notNull().default(''), version: integer().notNull().default(0), channel: text().notNull(), request_key: text(), request_hash: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('tasks_space').on(t.space_id), index('tasks_recipient').on(t.to_agent), index('tasks_actionable_page').on(t.to_agent,t.created_at,t.id).where(sql`${t.status} IN ('queued','working','needs_input')`), uniqueIndex('tasks_sender_request').on(t.from_agent,t.request_key)]);
export const changes = sqliteTable('changes', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), grant_id: text().notNull().references(() => grants.id), from_agent: text().notNull(), to_agent: text().notNull(), title: text().notNull(), previous: text().notNull(), instruction: text().notNull(), reason: text().notNull(), scope: text().notNull(), source_id: text(), status: text().notNull(), adopted: text(), version: integer().notNull().default(0), request_key: text(), request_hash: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('changes_space').on(t.space_id), index('changes_recipient').on(t.to_agent), index('changes_accepted_page').on(t.to_agent,t.updated_at,t.id).where(sql`${t.status}='accepted'`), uniqueIndex('changes_sender_request').on(t.from_agent,t.request_key)]);
export const events = sqliteTable('events', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), actor_id: text().notNull(), kind: text().notNull(), description: text().notNull(), created_at: text().notNull() }, t => [index('events_space_time').on(t.space_id, t.created_at)]);
export const invites = sqliteTable('invites', { code_hash: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), email: text().notNull(), role: text().notNull(), expires_at: text().notNull(), used_by: text(), created_by: text(), issued_version: integer().notNull().default(0) });

export const hostVisits = sqliteTable('host_visits', { id: text().primaryKey(), owner_id: text().notNull(), agent_id: text().references(() => agents.id), purpose: text().notNull(), service: text().notNull(), status: text().notNull(), room_id: text().references(() => spaces.id), outcome: text(), request_key: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('host_visits_owner_updated').on(t.owner_id,t.updated_at), index('host_visits_agent_page').on(t.owner_id,t.agent_id,t.created_at,t.id), uniqueIndex('host_visits_request').on(t.owner_id,t.request_key)]);

export const taskUpdates = sqliteTable('task_updates', { id: text().primaryKey(), task_id: text().notNull().references(() => tasks.id), version: integer().notNull(), status: text().notNull(), feedback: text().notNull(), actor_id: text(), agent_id: text(), channel: text().notNull(), request_key: text(), request_hash: text(), created_at: text().notNull() }, t => [uniqueIndex('task_updates_version').on(t.task_id,t.version), uniqueIndex('task_updates_request').on(t.task_id,t.request_key)]);

export const contextDecisions = sqliteTable('context_decisions', { id: text().primaryKey(), change_id: text().notNull().references(() => changes.id), version: integer().notNull(), status: text().notNull(), adopted: text(), note: text(), actor_id: text(), channel: text().notNull(), source_id: text(), source_version: integer(), source_status: text(), request_key: text(), request_hash: text(), created_at: text().notNull() }, t => [uniqueIndex('context_decisions_version').on(t.change_id,t.version), uniqueIndex('context_decisions_request').on(t.change_id,t.request_key)]);

export const creationRequests = sqliteTable('creation_requests', { actor_id: text().notNull(), action: text().notNull(), request_key: text().notNull(), request_hash: text().notNull(), resource_id: text().notNull(), created_at: text().notNull() }, t => [primaryKey({ columns: [t.actor_id,t.action,t.request_key] })]);

export const membershipChanges = sqliteTable('membership_changes', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), target_user_id: text().notNull(), membership_key: text().notNull(), actor_id: text().notNull(), action: text().notNull(), request_key: text().notNull(), request_hash: text().notNull(), space_version: integer().notNull(), created_at: text().notNull() }, t => [uniqueIndex('membership_changes_request').on(t.actor_id,t.request_key),index('membership_changes_target').on(t.space_id,t.target_user_id,t.space_version)]);

export const providerConnections = sqliteTable('provider_connections', { owner_id: text().notNull(), provider: text().notNull(), connection_id: text().notNull(), credential: text(), account_label: text(), status: text().notNull(), version: integer().notNull().default(0), refresh_key: text(), refresh_until: text(), updated_at: text().notNull() }, t => [primaryKey({columns:[t.owner_id,t.provider]})]);
export const providerOauthFlows = sqliteTable('provider_oauth_flows', { state_hash: text().primaryKey(), owner_id: text().notNull(), provider: text().notNull(), details: text(), status: text().notNull(), created_at: text().notNull(), expires_at: text().notNull() }, t => [index('provider_oauth_owner').on(t.owner_id,t.provider,t.created_at)]);
export const providerImportDrafts = sqliteTable('provider_import_drafts', { id: text().primaryKey(), owner_id: text().notNull(), connection_id: text().notNull(), content: text().notNull(), source_id: text(), shared_space_id: text(), request_hash: text(), created_at: text().notNull(), expires_at: text().notNull() }, t => [index('provider_drafts_owner').on(t.owner_id,t.created_at)]);
