import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const people = sqliteTable('people', { id: text().primaryKey(), email: text().notNull(), name: text().notNull() });
export const spaces = sqliteTable('spaces', { id: text().primaryKey(), owner_id: text().notNull(), name: text().notNull(), purpose: text().notNull(), topic: text().notNull(), created_at: text().notNull() });
export const members = sqliteTable('members', { space_id: text().notNull().references(() => spaces.id), user_id: text().notNull(), role: text().notNull() }, t => [primaryKey({ columns: [t.space_id, t.user_id] }), index('members_user').on(t.user_id)]);
export const agents = sqliteTable('agents', { id: text().primaryKey(), owner_id: text().notNull(), name: text().notNull(), provider: text().notNull(), status: text().notNull().default('pending'), last_seen_at: text(), created_at: text().notNull() }, t => [index('agents_owner').on(t.owner_id)]);
export const spaceAgents = sqliteTable('space_agents', { space_id: text().notNull().references(() => spaces.id), agent_id: text().notNull().references(() => agents.id) }, t => [primaryKey({ columns: [t.space_id, t.agent_id] })]);
export const grants = sqliteTable('grants', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), from_agent: text().notNull().references(() => agents.id), to_agent: text().notNull().references(() => agents.id), scope: text().notNull(), allow_assign: integer().notNull(), allow_context: integer().notNull(), status: text().notNull(), expires_at: text().notNull(), created_at: text().notNull() }, t => [index('grants_space').on(t.space_id)]);
export const sources = sqliteTable('sources', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), title: text().notNull(), content: text().notNull(), kind: text().notNull(), created_by: text().notNull(), created_at: text().notNull() }, t => [index('sources_space').on(t.space_id)]);
export const tasks = sqliteTable('tasks', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), grant_id: text().notNull().references(() => grants.id), from_agent: text().notNull(), to_agent: text().notNull(), title: text().notNull(), body: text().notNull(), status: text().notNull(), feedback: text().notNull().default(''), channel: text().notNull(), request_key: text(), request_hash: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('tasks_space').on(t.space_id), index('tasks_recipient').on(t.to_agent), uniqueIndex('tasks_sender_request').on(t.from_agent,t.request_key)]);
export const changes = sqliteTable('changes', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), grant_id: text().notNull().references(() => grants.id), from_agent: text().notNull(), to_agent: text().notNull(), title: text().notNull(), previous: text().notNull(), instruction: text().notNull(), reason: text().notNull(), scope: text().notNull(), source_id: text(), status: text().notNull(), adopted: text(), version: integer().notNull().default(0), request_key: text(), request_hash: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('changes_space').on(t.space_id), index('changes_recipient').on(t.to_agent), uniqueIndex('changes_sender_request').on(t.from_agent,t.request_key)]);
export const events = sqliteTable('events', { id: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), actor_id: text().notNull(), kind: text().notNull(), description: text().notNull(), created_at: text().notNull() }, t => [index('events_space_time').on(t.space_id, t.created_at)]);
export const invites = sqliteTable('invites', { code_hash: text().primaryKey(), space_id: text().notNull().references(() => spaces.id), email: text().notNull(), role: text().notNull(), expires_at: text().notNull(), used_by: text() });

export const hostVisits = sqliteTable('host_visits', { id: text().primaryKey(), owner_id: text().notNull(), agent_id: text().references(() => agents.id), purpose: text().notNull(), service: text().notNull(), status: text().notNull(), room_id: text().references(() => spaces.id), outcome: text(), request_key: text(), created_at: text().notNull(), updated_at: text().notNull() }, t => [index('host_visits_owner_updated').on(t.owner_id,t.updated_at), uniqueIndex('host_visits_request').on(t.owner_id,t.request_key)]);
